/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/onboarding`; params?: Router.UnknownInputParams; } | { pathname: `/sheet`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(drawer)'}${'/(home)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(drawer)'}/settings/devpage` | `/settings/devpage`; params?: Router.UnknownInputParams; } | { pathname: `${'/(drawer)'}/settings` | `/settings`; params?: Router.UnknownInputParams; } | { pathname: `${'/(drawer)'}/settings/livekit-assistant` | `/settings/livekit-assistant`; params?: Router.UnknownInputParams; } | { pathname: `${'/(drawer)'}/settings/livekit` | `/settings/livekit`; params?: Router.UnknownInputParams; } | { pathname: `${'/(drawer)'}/voicememo` | `/voicememo`; params?: Router.UnknownInputParams; } | { pathname: `${'/(drawer)'}/voicememo/record` | `/voicememo/record`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/onboarding`; params?: Router.UnknownOutputParams; } | { pathname: `/sheet`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(drawer)'}${'/(home)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(drawer)'}/settings/devpage` | `/settings/devpage`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(drawer)'}/settings` | `/settings`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(drawer)'}/settings/livekit-assistant` | `/settings/livekit-assistant`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(drawer)'}/settings/livekit` | `/settings/livekit`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(drawer)'}/voicememo` | `/voicememo`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(drawer)'}/voicememo/record` | `/voicememo/record`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } };
      href: Router.RelativePathString | Router.ExternalPathString | `/onboarding${`?${string}` | `#${string}` | ''}` | `/sheet${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(drawer)'}${'/(home)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(drawer)'}/settings/devpage${`?${string}` | `#${string}` | ''}` | `/settings/devpage${`?${string}` | `#${string}` | ''}` | `${'/(drawer)'}/settings${`?${string}` | `#${string}` | ''}` | `/settings${`?${string}` | `#${string}` | ''}` | `${'/(drawer)'}/settings/livekit-assistant${`?${string}` | `#${string}` | ''}` | `/settings/livekit-assistant${`?${string}` | `#${string}` | ''}` | `${'/(drawer)'}/settings/livekit${`?${string}` | `#${string}` | ''}` | `/settings/livekit${`?${string}` | `#${string}` | ''}` | `${'/(drawer)'}/voicememo${`?${string}` | `#${string}` | ''}` | `/voicememo${`?${string}` | `#${string}` | ''}` | `${'/(drawer)'}/voicememo/record${`?${string}` | `#${string}` | ''}` | `/voicememo/record${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/onboarding`; params?: Router.UnknownInputParams; } | { pathname: `/sheet`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(drawer)'}${'/(home)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(drawer)'}/settings/devpage` | `/settings/devpage`; params?: Router.UnknownInputParams; } | { pathname: `${'/(drawer)'}/settings` | `/settings`; params?: Router.UnknownInputParams; } | { pathname: `${'/(drawer)'}/settings/livekit-assistant` | `/settings/livekit-assistant`; params?: Router.UnknownInputParams; } | { pathname: `${'/(drawer)'}/settings/livekit` | `/settings/livekit`; params?: Router.UnknownInputParams; } | { pathname: `${'/(drawer)'}/voicememo` | `/voicememo`; params?: Router.UnknownInputParams; } | { pathname: `${'/(drawer)'}/voicememo/record` | `/voicememo/record`; params?: Router.UnknownInputParams; } | `/+not-found${`?${string}` | `#${string}` | ''}` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
    }
  }
}
