import { defineTable } from "convex/server";
import { v } from "convex/values";

/**
 * Demo Agent Tables
 *
 * Tables for tracking AI agent usage and sessions.
 * All table names are prefixed with `lifeos_demoAgent` to avoid conflicts.
 */

/**
 * Token usage validator matching AI SDK usage structure
 */
export const vTokenUsage = v.object({
  promptTokens: v.number(),
  completionTokens: v.number(),
  totalTokens: v.number(),
});

export const demoAgentTables = {
  // ==================== DEMO AGENT USAGE ====================
  /**
   * Tracks token usage for each AI agent call.
   * Used for billing, analytics, and monitoring.
   */
  lifeos_demoAgentUsage: defineTable({
    // Thread ID from the agent
    threadId: v.string(),
    // Agent name
    agentName: v.string(),
    // Model used (e.g., "openai/gpt-5-nano")
    model: v.string(),
    // Provider name (e.g., "openai", "google", "anthropic")
    provider: v.string(),
    // Token usage
    usage: vTokenUsage,
    // Optional provider-specific metadata
    providerMetadata: v.optional(v.any()),
    // Timestamp
    createdAt: v.number(),
  })
    .index("by_thread", ["threadId"])
    .index("by_thread_created", ["threadId", "createdAt"])
    .index("by_model", ["model"])
    .index("by_created", ["createdAt"]),

  // ==================== DEMO AGENT SESSION USAGE ====================
  /**
   * Aggregated usage per session (frontend session, not thread).
   * Useful for displaying cumulative usage in the UI.
   */
  lifeos_demoAgentSessionUsage: defineTable({
    // Session ID (generated by frontend)
    sessionId: v.string(),
    // Thread ID (optional, may have multiple threads per session)
    threadId: v.optional(v.string()),
    // Cumulative token usage for this session
    totalPromptTokens: v.number(),
    totalCompletionTokens: v.number(),
    totalTokens: v.number(),
    // Number of messages in session
    messageCount: v.number(),
    // Last model used
    lastModel: v.optional(v.string()),
    // Timestamps
    createdAt: v.number(),
    updatedAt: v.number(),
  })
    .index("by_session", ["sessionId"])
    .index("by_thread", ["threadId"]),
};
