import { defineTable } from "convex/server";
import { v } from "convex/values";

/**
 * LifeOS Tables
 *
 * Tables for the LifeOS personal productivity app.
 * All table names are prefixed with `life_` to avoid conflicts.
 */
export const lifeosTables = {
  // ==================== YOUTUBE PLAYLISTS ====================
  life_youtubePlaylists: defineTable({
    // User who owns this playlist sync
    userId: v.id("users"),
    // YouTube playlist ID (e.g., "PLxxx...")
    youtubePlaylistId: v.string(),
    // Playlist title
    title: v.string(),
    // Playlist description
    description: v.optional(v.string()),
    // Channel that owns the playlist
    channelTitle: v.optional(v.string()),
    // Number of videos in playlist
    videoCount: v.optional(v.number()),
    // Playlist thumbnail URL
    thumbnailUrl: v.optional(v.string()),
    // Last time this playlist was synced
    lastSyncedAt: v.number(),
    // Timestamps
    createdAt: v.number(),
  })
    .index("by_user", ["userId"])
    .index("by_youtube_id", ["youtubePlaylistId"])
    .index("by_user_youtube_id", ["userId", "youtubePlaylistId"]),

  // ==================== YOUTUBE VIDEOS ====================
  life_youtubeVideos: defineTable({
    // User who owns this video sync
    userId: v.id("users"),
    // Reference to playlist (optional - video might be standalone)
    playlistId: v.optional(v.id("life_youtubePlaylists")),
    // YouTube video ID (e.g., "dQw4w9WgXcQ")
    youtubeVideoId: v.string(),
    // Video title
    title: v.string(),
    // Video description
    description: v.optional(v.string()),
    // Channel name
    channelTitle: v.optional(v.string()),
    // Duration in seconds
    duration: v.optional(v.number()),
    // Thumbnail URL
    thumbnailUrl: v.optional(v.string()),
    // When the video was published on YouTube
    publishedAt: v.optional(v.string()),
    // Whether we have a transcript for this video
    hasTranscript: v.boolean(),
    // Timestamps
    createdAt: v.number(),
  })
    .index("by_user", ["userId"])
    .index("by_youtube_id", ["youtubeVideoId"])
    .index("by_user_youtube_id", ["userId", "youtubeVideoId"])
    .index("by_playlist", ["playlistId"]),

  // ==================== YOUTUBE TRANSCRIPTS ====================
  life_youtubeTranscripts: defineTable({
    // User who owns this transcript
    userId: v.id("users"),
    // Reference to the video
    videoId: v.id("life_youtubeVideos"),
    // YouTube video ID (denormalized for easier queries)
    youtubeVideoId: v.string(),
    // Language code (e.g., "en", "es", "zh")
    language: v.string(),
    // Whether this is auto-generated captions
    isAutoGenerated: v.boolean(),
    // Full transcript text (concatenated)
    transcript: v.string(),
    // Timed segments for precise lookups
    segments: v.optional(
      v.array(
        v.object({
          start: v.number(), // Start time in seconds
          duration: v.number(), // Duration in seconds
          text: v.string(), // Segment text
        })
      )
    ),
    // Timestamps
    createdAt: v.number(),
    updatedAt: v.number(),
  })
    .index("by_user", ["userId"])
    .index("by_video", ["videoId"])
    .index("by_youtube_id", ["youtubeVideoId"])
    .index("by_user_youtube_id", ["userId", "youtubeVideoId"]),
};
