"""
Convex Sync Client with Clerk JWT Authentication

Handles syncing YouTube data to Convex backend.
"""

from typing import Optional
from dataclasses import asdict

from convex import ConvexClient

from .config import load_config, load_clerk_auth, update_last_sync
from .youtube_scraper import PlaylistInfo, VideoInfo, Transcript, TranscriptSegment


class ConvexSyncError(Exception):
    """Error during Convex sync"""
    pass


class AuthenticationError(ConvexSyncError):
    """Authentication failed - session may have expired"""
    pass


def get_jwt_token() -> str:
    """
    Get a fresh JWT token from Clerk.

    This uses the Clerk Backend SDK to generate a JWT token
    using the stored session ID.
    """
    from clerk_backend_api import Clerk

    auth = load_clerk_auth()

    if not auth.secret_key:
        raise AuthenticationError("Clerk secret key not configured")

    if not auth.session_id:
        raise AuthenticationError("Clerk session ID not configured. Please login first.")

    try:
        with Clerk(bearer_auth=auth.secret_key) as clerk:
            # Get JWT token using the "convex" template
            response = clerk.sessions.get_token(
                session_id=auth.session_id,
                template="convex"
            )

            if not response or not response.jwt:
                raise AuthenticationError("Failed to get JWT token from Clerk")

            return response.jwt

    except Exception as e:
        error_msg = str(e)
        if "session" in error_msg.lower() or "expired" in error_msg.lower():
            raise AuthenticationError(f"Session expired or invalid: {e}")
        raise ConvexSyncError(f"Failed to get JWT token: {e}")


def create_convex_client() -> ConvexClient:
    """Create an authenticated Convex client"""
    config = load_config()

    if not config.convex_url:
        raise ConvexSyncError("Convex URL not configured")

    # Get fresh JWT token
    jwt_token = get_jwt_token()

    # Create client and set auth
    client = ConvexClient(config.convex_url)
    client.set_auth(jwt_token)

    return client


def sync_playlist(playlist_info: PlaylistInfo) -> Optional[str]:
    """
    Sync a playlist to Convex.

    Returns the playlist ID in Convex, or None if failed.
    """
    try:
        client = create_convex_client()

        result = client.mutation("lifeos/youtube:upsertPlaylist", {
            "youtubePlaylistId": playlist_info.youtube_playlist_id,
            "title": playlist_info.title,
            "description": playlist_info.description,
            "channelTitle": playlist_info.channel_title,
            "videoCount": playlist_info.video_count,
            "thumbnailUrl": playlist_info.thumbnail_url,
        })

        return result

    except Exception as e:
        print(f"Failed to sync playlist {playlist_info.youtube_playlist_id}: {e}")
        raise


def sync_video(video_info: VideoInfo, playlist_id: Optional[str] = None) -> Optional[str]:
    """
    Sync a video to Convex.

    Returns the video ID in Convex, or None if failed.
    """
    try:
        client = create_convex_client()

        result = client.mutation("lifeos/youtube:upsertVideo", {
            "playlistId": playlist_id,
            "youtubeVideoId": video_info.youtube_video_id,
            "title": video_info.title,
            "description": video_info.description,
            "channelTitle": video_info.channel_title,
            "duration": video_info.duration,
            "thumbnailUrl": video_info.thumbnail_url,
            "publishedAt": video_info.published_at,
            "hasTranscript": False,  # Will be updated when transcript is synced
        })

        return result

    except Exception as e:
        print(f"Failed to sync video {video_info.youtube_video_id}: {e}")
        raise


def sync_transcript(
    transcript: Transcript,
    video_id: str,
    youtube_video_id: str
) -> Optional[str]:
    """
    Sync a transcript to Convex.

    Args:
        transcript: The transcript data
        video_id: The Convex video document ID
        youtube_video_id: The YouTube video ID

    Returns the transcript ID in Convex, or None if failed.
    """
    try:
        client = create_convex_client()

        # Convert segments to dict format
        segments_data = [
            {
                "start": seg.start,
                "duration": seg.duration,
                "text": seg.text,
            }
            for seg in transcript.segments
        ]

        result = client.mutation("lifeos/youtube:upsertTranscript", {
            "videoId": video_id,
            "youtubeVideoId": youtube_video_id,
            "language": transcript.language,
            "isAutoGenerated": transcript.is_auto_generated,
            "transcript": transcript.full_text,
            "segments": segments_data,
        })

        # Also update the video to mark it as having a transcript
        client.mutation("lifeos/youtube:upsertVideo", {
            "youtubeVideoId": youtube_video_id,
            "title": "",  # These will be ignored in upsert if video exists
            "hasTranscript": True,
        })

        return result

    except Exception as e:
        print(f"Failed to sync transcript for {youtube_video_id}: {e}")
        raise


def get_existing_video(youtube_video_id: str) -> Optional[dict]:
    """Check if a video already exists in Convex"""
    try:
        client = create_convex_client()
        return client.query("lifeos/youtube:getVideoByYoutubeId", {
            "youtubeVideoId": youtube_video_id
        })
    except Exception as e:
        print(f"Failed to check existing video {youtube_video_id}: {e}")
        return None


def get_existing_transcript(youtube_video_id: str) -> Optional[dict]:
    """Check if a transcript already exists in Convex"""
    try:
        client = create_convex_client()
        return client.query("lifeos/youtube:getTranscriptByYoutubeId", {
            "youtubeVideoId": youtube_video_id
        })
    except Exception as e:
        print(f"Failed to check existing transcript {youtube_video_id}: {e}")
        return None


def full_sync(
    progress_callback: Optional[callable] = None
) -> dict:
    """
    Perform a full sync of all configured playlists.

    Args:
        progress_callback: Optional callback function(message: str) for progress updates

    Returns:
        Dict with sync statistics
    """
    from .youtube_scraper import (
        get_playlist_info,
        get_playlist_videos,
        get_transcript,
    )

    config = load_config()
    stats = {
        "playlists_synced": 0,
        "videos_synced": 0,
        "transcripts_synced": 0,
        "errors": [],
    }

    def log(msg: str):
        print(msg)
        if progress_callback:
            progress_callback(msg)

    if not config.playlist_ids:
        log("No playlists configured")
        return stats

    for playlist_id in config.playlist_ids:
        log(f"Syncing playlist: {playlist_id}")

        try:
            # Get playlist info
            playlist_info = get_playlist_info(playlist_id)
            if not playlist_info:
                stats["errors"].append(f"Failed to get playlist info: {playlist_id}")
                continue

            # Sync playlist metadata
            convex_playlist_id = sync_playlist(playlist_info)
            stats["playlists_synced"] += 1
            log(f"  Playlist synced: {playlist_info.title}")

            # Get videos in playlist
            videos = get_playlist_videos(playlist_id)
            log(f"  Found {len(videos)} videos")

            for video in videos:
                try:
                    # Check if video already has transcript
                    existing_transcript = get_existing_transcript(video.youtube_video_id)

                    if existing_transcript:
                        log(f"    Skipping {video.title} (already has transcript)")
                        continue

                    # Sync video
                    convex_video_id = sync_video(video, convex_playlist_id)
                    stats["videos_synced"] += 1
                    log(f"    Video synced: {video.title}")

                    # Get and sync transcript
                    transcript = get_transcript(
                        video.youtube_video_id,
                        config.preferred_language
                    )

                    if transcript:
                        sync_transcript(transcript, convex_video_id, video.youtube_video_id)
                        stats["transcripts_synced"] += 1
                        log(f"    Transcript synced ({transcript.language})")
                    else:
                        log(f"    No transcript available")

                except Exception as e:
                    error_msg = f"Error syncing video {video.youtube_video_id}: {e}"
                    stats["errors"].append(error_msg)
                    log(f"    Error: {e}")

        except AuthenticationError as e:
            stats["errors"].append(f"Authentication error: {e}")
            log(f"Authentication error: {e}")
            break  # Stop sync if auth fails

        except Exception as e:
            error_msg = f"Error syncing playlist {playlist_id}: {e}"
            stats["errors"].append(error_msg)
            log(f"  Error: {e}")

    # Update last sync timestamp
    update_last_sync()

    log(f"Sync complete: {stats['playlists_synced']} playlists, "
        f"{stats['videos_synced']} videos, {stats['transcripts_synced']} transcripts")

    return stats


def test_connection() -> tuple[bool, str]:
    """
    Test the Convex connection and authentication.

    Returns:
        Tuple of (success, message)
    """
    try:
        client = create_convex_client()

        # Try to query playlists (will fail if not authenticated)
        client.query("lifeos/youtube:getPlaylists", {})

        return True, "Connection successful!"

    except AuthenticationError as e:
        return False, f"Authentication failed: {e}"

    except ConvexSyncError as e:
        return False, f"Configuration error: {e}"

    except Exception as e:
        return False, f"Connection failed: {e}"
