#!/bin/bash
# Auto-updates devcontainer.json and setup.sh with node_modules mounts
# Run automatically via dcenter/dcyolo, or manually when adding packages

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(dirname "$SCRIPT_DIR")"
DEVCONTAINER_FILE="$SCRIPT_DIR/devcontainer.json"
SETUP_FILE="$SCRIPT_DIR/setup.sh"
CACHE_FILE="$SCRIPT_DIR/.mounts-hash"

# Project name for volume prefixes (lowercase, alphanumeric + dash)
PROJECT_NAME=$(basename "$REPO_ROOT" | tr '[:upper:]' '[:lower:]' | sed 's/[^a-z0-9-]/-/g')

# Force update with -f flag
FORCE_UPDATE=false
[[ "${1:-}" == "-f" ]] && FORCE_UPDATE=true

# Find all directories with package.json (excluding node_modules, build outputs, root)
find_packages() {
    find "$REPO_ROOT" -name "package.json" -type f \
        -not -path "*/node_modules/*" \
        -not -path "*/.git/*" \
        -not -path "*/.next/*" \
        -not -path "*/dist/*" \
        -not -path "*/build/*" \
        -not -path "*/.mastra/*" \
        -not -path "*/out/*" \
        -not -path "$REPO_ROOT/package.json" \
        | while read -r pkg_file; do
            dir=$(dirname "$pkg_file")
            echo "${dir#$REPO_ROOT/}"
        done
}

# Generate mounts array content (without brackets)
generate_mounts_content() {
    echo '    "source=claude-credentials-${localEnv:USER},target=/home/vscode/.claude-shared,type=volume",'
    echo "    \"source=${PROJECT_NAME}-pnpm-store,target=/workspace/.pnpm-store,type=volume\","
    echo "    \"source=${PROJECT_NAME}-node-modules-root,target=/workspace/node_modules,type=volume\","

    local packages=$(find_packages | sort -u)
    local last_pkg=$(echo "$packages" | tail -1)

    echo "$packages" | while read -r pkg_path; do
        [ -z "$pkg_path" ] && continue
        vol_name=$(echo "$pkg_path" | tr '/' '-' | tr '[:upper:]' '[:lower:]')
        if [ "$pkg_path" = "$last_pkg" ]; then
            # Last entry - no trailing comma
            echo "    \"source=${PROJECT_NAME}-node-modules-${vol_name},target=/workspace/${pkg_path}/node_modules,type=volume\""
        else
            echo "    \"source=${PROJECT_NAME}-node-modules-${vol_name},target=/workspace/${pkg_path}/node_modules,type=volume\","
        fi
    done
}

# Generate chown commands
generate_chowns() {
    echo 'sudo chown -R vscode:vscode /workspace/.pnpm-store 2>/dev/null || true'
    echo 'sudo chown -R vscode:vscode /workspace/node_modules 2>/dev/null || true'

    find_packages | sort -u | while read -r pkg_path; do
        [ -z "$pkg_path" ] && continue
        echo "sudo chown -R vscode:vscode /workspace/${pkg_path}/node_modules 2>/dev/null || true"
    done
}

# Update devcontainer.json
update_devcontainer() {
    local temp_file=$(mktemp)
    local in_mounts=false

    while IFS= read -r line; do
        if [[ "$line" =~ ^[[:space:]]*\"mounts\":[[:space:]]*\[ ]]; then
            # Start of mounts array
            in_mounts=true
            echo '  "mounts": [' >> "$temp_file"
            generate_mounts_content >> "$temp_file"
            echo '  ],' >> "$temp_file"
        elif $in_mounts; then
            # Skip lines until we find the closing bracket
            if [[ "$line" =~ ^[[:space:]]*\], ]] || [[ "$line" =~ ^[[:space:]]*\][[:space:]]*$ ]]; then
                in_mounts=false
            fi
        else
            echo "$line" >> "$temp_file"
        fi
    done < "$DEVCONTAINER_FILE"

    mv "$temp_file" "$DEVCONTAINER_FILE"
}

# Update setup.sh chown section (between markers)
update_setup() {
    local temp_file=$(mktemp)
    local in_section=false

    while IFS= read -r line; do
        if [[ "$line" == "# Fix ownership of all node_modules volumes" ]]; then
            # Start marker - write new section
            echo "# Fix ownership of all node_modules volumes" >> "$temp_file"
            echo "# AUTO-GENERATED by generate-mounts.sh - do not edit manually" >> "$temp_file"
            generate_chowns >> "$temp_file"
            echo "# END AUTO-GENERATED" >> "$temp_file"
            in_section=true
        elif [[ "$line" == "# END AUTO-GENERATED" ]]; then
            # End marker - stop skipping
            in_section=false
        elif $in_section; then
            # Skip lines between markers
            continue
        else
            echo "$line" >> "$temp_file"
        fi
    done < "$SETUP_FILE"

    mv "$temp_file" "$SETUP_FILE"
    chmod +x "$SETUP_FILE"
}

# Check if any package.json is newer than the cache file (fast mtime check)
needs_update() {
    [[ "$FORCE_UPDATE" == "true" ]] && return 0
    [[ ! -f "$CACHE_FILE" ]] && return 0

    # Only check apps/ and packages/ directories (where workspaces live)
    local newer=""
    for dir in "$REPO_ROOT/apps" "$REPO_ROOT/packages"; do
        [[ -d "$dir" ]] || continue
        newer=$(find "$dir" -maxdepth 3 -name "package.json" -type f \
            -not -path "*/node_modules/*" \
            -newer "$CACHE_FILE" \
            -print -quit 2>/dev/null)
        [[ -n "$newer" ]] && return 0
    done
    return 1
}

# Main
if ! needs_update; then
    echo "✓ Mounts up-to-date"
    exit 0
fi

echo "=== Updating devcontainer mounts for $PROJECT_NAME ==="

PACKAGES=$(find_packages | sort -u)
PKG_COUNT=$(echo "$PACKAGES" | grep -c . || echo 0)
echo "Found $PKG_COUNT packages"

echo "Updating devcontainer.json..."
update_devcontainer

echo "Updating setup.sh..."
update_setup

# Update cache timestamp
touch "$CACHE_FILE"

echo "Done!"
