#!/bin/bash
set -euo pipefail

echo "=== Setting up devcontainer ==="

# Ensure directories exist with correct ownership
mkdir -p "$HOME/.claude"
mkdir -p "$HOME/.claude-shared/auth"
mkdir -p "$HOME/.local/bin"

# Fix ownership of shared volume (in case it was created by root)
sudo chown -R vscode:vscode /home/vscode/.claude-shared 2>/dev/null || true

# Fix ownership of all node_modules volumes
# AUTO-GENERATED by generate-mounts.sh - do not edit manually
sudo chown -R vscode:vscode /workspace/.pnpm-store 2>/dev/null || true
sudo chown -R vscode:vscode /workspace/node_modules 2>/dev/null || true
sudo chown -R vscode:vscode /workspace/apps/lifeos/taurireact-macapp/node_modules 2>/dev/null || true
sudo chown -R vscode:vscode /workspace/apps/lifeos/taurireact-macapp/plugins/capacitor-clerk-native/node_modules 2>/dev/null || true
sudo chown -R vscode:vscode /workspace/packages/beeperdb/node_modules 2>/dev/null || true
sudo chown -R vscode:vscode /workspace/packages/chrome_exts/inspiration_ext/node_modules 2>/dev/null || true
sudo chown -R vscode:vscode /workspace/packages/holaaiconvex/node_modules 2>/dev/null || true
sudo chown -R vscode:vscode /workspace/packages/lifeos-mcp/node_modules 2>/dev/null || true
sudo chown -R vscode:vscode /workspace/packages/livekit-voice-agent/node_modules 2>/dev/null || true
# END AUTO-GENERATED

# Install pnpm globally
echo "Installing pnpm..."
npm install -g pnpm@10.20.0

# Install Claude Code CLI
echo "Installing Claude Code CLI..."
npm install -g @anthropic-ai/claude-code

# Get the actual claude binary path
CLAUDE_BIN=$(which claude)
echo "Claude CLI installed at: $CLAUDE_BIN"

# Create a wrapper script to handle empty env vars
cat > "$HOME/.local/bin/claude-wrapper" << 'WRAPPER_EOF'
#!/bin/bash
set -euo pipefail

# Fix HOME if unset
if [ -z "${HOME:-}" ] || [ ! -d "${HOME:-}" ]; then
  export HOME="/home/vscode"
fi

# Unset empty tokens so file-based auth takes precedence
if [[ -v CLAUDE_CODE_OAUTH_TOKEN && -z "${CLAUDE_CODE_OAUTH_TOKEN}" ]]; then
  unset CLAUDE_CODE_OAUTH_TOKEN
fi
if [[ -v CLAUDE_API_KEY && -z "${CLAUDE_API_KEY}" ]]; then
  unset CLAUDE_API_KEY
fi

exec claude-real "$@"
WRAPPER_EOF

chmod +x "$HOME/.local/bin/claude-wrapper"

# Rename the actual claude and symlink wrapper (only if not already done)
if [ ! -f "$HOME/.local/bin/claude-real" ]; then
  # Create a symlink to the real claude
  ln -sf "$CLAUDE_BIN" "$HOME/.local/bin/claude-real"
fi

# Create save-claude-auth script (also saves gh and ssh)
cat > "$HOME/save-auth.sh" << 'SAVE_EOF'
#!/bin/bash
set -euo pipefail

echo "Saving credentials to shared volume..."

sudo chown -R vscode:vscode /home/vscode/.claude-shared 2>/dev/null || true
mkdir -p /home/vscode/.claude-shared/auth
mkdir -p /home/vscode/.claude-shared/ssh
mkdir -p /home/vscode/.claude-shared/gh

# === Claude credentials ===
echo ""
echo "=== Claude ==="
if [ -f "$HOME/.claude/.credentials.json" ]; then
  cp -p "$HOME/.claude/.credentials.json" /home/vscode/.claude-shared/auth/credentials.json
  echo "✓ Saved: ~/.claude/.credentials.json"
else
  echo "✗ Missing: ~/.claude/.credentials.json (run 'claude login' first)"
fi

if [ -f "$HOME/.claude.json" ]; then
  cp -p "$HOME/.claude.json" /home/vscode/.claude-shared/auth/claude.json
  echo "✓ Saved: ~/.claude.json"
fi

if [ -f "$HOME/.claude/settings.json" ]; then
  cp -p "$HOME/.claude/settings.json" /home/vscode/.claude-shared/auth/settings.json
  echo "✓ Saved: ~/.claude/settings.json"
fi

# === SSH keys ===
echo ""
echo "=== SSH ==="
if [ -d "$HOME/.ssh" ]; then
  cp -rp "$HOME/.ssh/"* /home/vscode/.claude-shared/ssh/ 2>/dev/null || true
  echo "✓ Saved: ~/.ssh/* (keys and config)"
else
  echo "✗ Missing: ~/.ssh directory"
fi

# === GitHub CLI auth ===
echo ""
echo "=== GitHub CLI ==="
if [ -d "$HOME/.config/gh" ]; then
  cp -rp "$HOME/.config/gh/"* /home/vscode/.claude-shared/gh/ 2>/dev/null || true
  echo "✓ Saved: ~/.config/gh/* (gh auth)"
else
  echo "✗ Missing: ~/.config/gh (run 'gh auth login' first)"
fi

# === Git config ===
echo ""
echo "=== Git config ==="
if [ -f "$HOME/.gitconfig" ]; then
  cp -p "$HOME/.gitconfig" /home/vscode/.claude-shared/auth/gitconfig
  echo "✓ Saved: ~/.gitconfig"
fi

# === Convex credentials ===
echo ""
echo "=== Convex ==="
mkdir -p /home/vscode/.claude-shared/convex
if [ -d "$HOME/.convex" ] && [ "$(ls -A "$HOME/.convex" 2>/dev/null)" ]; then
  cp -rp "$HOME/.convex/"* /home/vscode/.claude-shared/convex/ 2>/dev/null || true
  echo "✓ Saved: ~/.convex/* (convex auth)"
else
  echo "✗ Missing: ~/.convex (run 'npx convex dev --once' first)"
fi

echo ""
echo "All credentials saved to: /home/vscode/.claude-shared/"
ls -la /home/vscode/.claude-shared/
SAVE_EOF

chmod +x "$HOME/save-auth.sh"

# Keep backward-compatible alias
ln -sf "$HOME/save-auth.sh" "$HOME/save-claude-auth.sh"

chmod +x "$HOME/save-claude-auth.sh"

# Restore any existing credentials
bash /workspace/.devcontainer/restore-claude-auth.sh

# Install project dependencies (non-interactive)
echo "Installing project dependencies..."
cd /workspace
if ! CI=true pnpm install --frozen-lockfile; then
  echo "pnpm install failed (skipping). Run it manually after fixing env/tooling issues."
fi

echo ""
echo "=== Setup complete ==="
echo ""
echo "First-time setup:"
echo "  1. Run: claude login"
echo "  2. Complete OAuth in browser"
echo "  3. Run: ~/save-auth.sh"
echo ""
echo "Credentials will persist across container rebuilds."
echo ""
