import { invoke } from "@tauri-apps/api/core";

export interface TranscriptSegment {
  start: number;
  duration: number;
  text: string;
}

export interface TranscriptResult {
  language: string;
  isAutoGenerated: boolean;
  transcript: string;
  segments: TranscriptSegment[];
}

interface RustTranscriptResult {
  language: string;
  is_auto_generated: boolean;
  transcript: string;
  segments: Array<{
    start: number;
    duration: number;
    text: string;
  }>;
}

export async function fetchTranscript(
  videoId: string
): Promise<TranscriptResult | null> {
  try {
    console.log("[transcript] Fetching transcript via Tauri command for:", videoId);

    const result = await invoke<RustTranscriptResult>("fetch_youtube_transcript", {
      videoId,
    });

    console.log("[transcript] Got result:", {
      language: result.language,
      isAutoGenerated: result.is_auto_generated,
      segmentsCount: result.segments.length,
    });

    if (!result.segments || result.segments.length === 0) {
      console.log("[transcript] No segments in result");
      return null;
    }

    return {
      language: result.language,
      isAutoGenerated: result.is_auto_generated,
      transcript: result.transcript,
      segments: result.segments,
    };
  } catch (error) {
    console.error("[transcript] Failed to fetch transcript:", error);
    return null;
  }
}
