import { useQuery } from "convex/react";
import { api, type Id } from "@holaai/convex";

interface TranscriptViewProps {
  videoId: Id<"life_youtubeVideos">;
  onClose: () => void;
}

export function TranscriptView({ videoId, onClose }: TranscriptViewProps) {
  const transcript = useQuery(api.lifeos.youtube.getTranscript, { videoId });

  if (transcript === undefined) {
    return (
      <div className="flex items-center justify-center h-full">
        <div className="spinner" />
      </div>
    );
  }

  if (transcript === null) {
    return (
      <div className="flex flex-col items-center justify-center h-full text-center p-4">
        <svg
          className="w-12 h-12 text-[var(--text-secondary)] mb-3"
          fill="none"
          stroke="currentColor"
          viewBox="0 0 24 24"
        >
          <path
            strokeLinecap="round"
            strokeLinejoin="round"
            strokeWidth={2}
            d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z"
          />
        </svg>
        <p className="text-[var(--text-secondary)]">
          No transcript available for this video.
        </p>
        <button
          onClick={onClose}
          className="mt-4 px-4 py-2 text-sm text-[var(--accent)] hover:underline"
        >
          Go back
        </button>
      </div>
    );
  }

  return (
    <div className="h-full flex flex-col">
      <div className="flex items-center justify-between mb-3 flex-shrink-0">
        <div className="flex items-center gap-2">
          <span className="text-xs px-2 py-1 bg-[var(--bg-secondary)] rounded">
            {transcript.language.toUpperCase()}
          </span>
          {transcript.isAutoGenerated && (
            <span className="text-xs text-[var(--text-secondary)]">
              Auto-generated
            </span>
          )}
        </div>
      </div>

      <div className="flex-1 overflow-y-auto">
        {transcript.segments && transcript.segments.length > 0 ? (
          <div className="space-y-2">
            {transcript.segments.map((segment, index) => (
              <div
                key={index}
                className="flex gap-3 p-2 rounded hover:bg-[var(--bg-secondary)] transition-colors"
              >
                <span className="text-xs text-[var(--text-secondary)] flex-shrink-0 w-12 pt-0.5">
                  {formatTimestamp(segment.start)}
                </span>
                <p className="text-sm leading-relaxed">{segment.text}</p>
              </div>
            ))}
          </div>
        ) : (
          <div className="prose prose-sm max-w-none">
            <p className="text-sm leading-relaxed whitespace-pre-wrap">
              {transcript.transcript}
            </p>
          </div>
        )}
      </div>
    </div>
  );
}

function formatTimestamp(seconds: number): string {
  const mins = Math.floor(seconds / 60);
  const secs = Math.floor(seconds % 60);
  return `${mins}:${secs.toString().padStart(2, "0")}`;
}
